---
- hosts: all
  tasks:
  - name: Ensure user bob is present
    win_user:
      name: billy
      password: B0bP4ssw0rd
      state: present
      groups:
        - Users
  - name: Install pkg git
    win_chocolatey:
      name: googlechrome
      state: present


